local util = require('tardis-nvim.util')

describe('util', function ()
    it('dirname', function ()
        assert.equal(util.dirname("/usr/bin/env"), '/usr/bin/')
        assert.equal(util.dirname("env"), '.')
        assert.equal(util.dirname("./something"), './')
    end)
    it('basename', function ()
        assert.equal(util.basename("/usr/bin/env"), 'env')
        assert.equal(util.basename("env"), 'env')
        assert.equal(util.basename("./something"), 'something')
    end)
end)
